"""add painel admin e mensagens whatsapp

Revision ID: 31695d377aa1
Revises: dd43923ccd09
Create Date: 2026-03-11 21:35:59.155523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31695d377aa1'
down_revision: Union[str, Sequence[str], None] = 'dd43923ccd09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagens_whatsapp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_escola', sa.UUID(), nullable=False),
    sa.Column('telefone_usuario', sa.String(length=30), nullable=False),
    sa.Column('tipo_mensagem', sa.String(length=20), nullable=False),
    sa.Column('conteudo', sa.String(), nullable=True),
    sa.Column('mensagem_id_whatsapp', sa.String(length=120), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_escola'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_admin',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_escola', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_escola'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_constraint(op.f('uq_conversation_tenant_user'), 'conversations', type_='unique')
    op.drop_column('conversations', 'data_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_conversation_tenant_user'), 'conversations', ['tenant_id', 'user_wa_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('usuarios_admin')
    op.drop_table('mensagens_whatsapp')
    # ### end Alembic commands ###
