"""add contexto_json em conversations

Revision ID: dd43923ccd09
Revises: 2a84c33230fd
Create Date: 2026-03-11 20:57:32.951099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd43923ccd09'
down_revision: Union[str, Sequence[str], None] = '2a84c33230fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        'conversations',
        sa.Column('contexto_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.execute("UPDATE conversations SET contexto_json = '{}'::jsonb WHERE contexto_json IS NULL")
    op.alter_column('conversations', 'contexto_json', nullable=False)

    
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_conversation_tenant_user'), 'conversations', ['tenant_id', 'user_wa_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('conversations', 'contexto_json')
    # ### end Alembic commands ###
